//
//  AppDelegateInteractor.swift
//  ChatWithFirebase
//
//  Created by Thuan Tran on 10/15/17.
//  Copyright (c) 2017 Thuan Tran. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol AppDelegateBusinessLogic
{
  func doSomething(request: AppDelegate1.Something.Request)
}

protocol AppDelegateDataStore
{
  //var name: String { get set }
}

class AppDelegateInteractor: AppDelegateBusinessLogic, AppDelegateDataStore
{
  var presenter: AppDelegatePresentationLogic?
  var worker: AppDelegateWorker?
  //var name: String = ""
  
  // MARK: Do something
  
  func doSomething(request: AppDelegate1.Something.Request)
  {
    worker = AppDelegateWorker()
    worker?.doSomeWork()
    
    let response = AppDelegate1.Something.Response()
    presenter?.presentSomething(response: response)
  }
}
