//
//  SignInInteractor.swift
//  ChatWithFirebase
//
//  Created by Thuan Tran on 10/15/17.
//  Copyright (c) 2017 Thuan Tran. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol SignInBusinessLogic
{
  func doSomething(request: SignIn.Something.Request)
}

protocol SignInDataStore
{
  //var name: String { get set }
}

class SignInInteractor: SignInBusinessLogic, SignInDataStore
{
  var presenter: SignInPresentationLogic?
  var worker: SignInWorker?
  //var name: String = ""
  
  // MARK: Do something
  
  func doSomething(request: SignIn.Something.Request)
  {
    worker = SignInWorker()
    worker?.doSomeWork()
    
    let response = SignIn.Something.Response()
    presenter?.presentSomething(response: response)
  }
}
