//
//  SignUpInteractor.swift
//  ChatWithFirebase
//
//  Created by Thuan Tran on 10/15/17.
//  Copyright (c) 2017 Thuan Tran. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol SignUpBusinessLogic
{
  func doSomething(request: SignUp.Something.Request)
}

protocol SignUpDataStore
{
  //var name: String { get set }
}

class SignUpInteractor: SignUpBusinessLogic, SignUpDataStore
{
  var presenter: SignUpPresentationLogic?
  var worker: SignUpWorker?
  //var name: String = ""
  
  // MARK: Do something
  
  func doSomething(request: SignUp.Something.Request)
  {
    worker = SignUpWorker()
    worker?.doSomeWork()
    
    let response = SignUp.Something.Response()
    presenter?.presentSomething(response: response)
  }
}
